function chain:phi/whole_inventory
function chain:phi/enderchest
function phi.modifyinv:load/hotbar
function phi.modifyinv:apply/hotbar
function phi.modifyinv:load/inventory
function phi.modifyinv:apply/inventory
function phi.modifyinv:load/armor
function phi.modifyinv:apply/armor
function phi.modifyinv:load/offhand
function phi.modifyinv:apply/offhand
function phi.modifyinv:load/enderchest
function phi.modifyinv:apply/enderchest
